import type { Patient } from '../types';

// Simple dataset with at least 10 patients for each department
export const departmentPatients: Patient[] = [
  // Cardiology Department (10 patients)
  {
    id: 'CARD001',
    name: 'Rajesh Kumar',
    age: 58,
    gender: 'Male',
    dob: '1965-03-15',
    bloodType: 'O+',
    maritalStatus: 'Married',
    guardianName: 'Sunita Kumar',
    phoneNumber: '9876543210',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pain', 'Shortness of breath'],
    surgeries: ['Angioplasty (2019)'],
    triageInfo: {
      chiefComplaint: 'Chest pain and shortness of breath',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient presents with chest pain and shortness of breath. ECG shows ST-segment changes.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC101', condition: 'Hypertension', diagnosedDate: '2015-01-01' },
        { id: 'PC102', condition: 'Diabetes', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [
        { id: 'S101', procedure: 'Angioplasty', date: '2019-05-20' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 92,
    respiration_rate: 22,
    bp_systolic: 145,
    bp_diastolic: 90,
  },
  {
    id: 'CARD002',
    name: 'Priya Sharma',
    age: 45,
    gender: 'Female',
    dob: '1978-07-22',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Ramesh Sharma',
    phoneNumber: '9876543211',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Palpitations', 'Dizziness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Palpitations and dizziness',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient reports frequent palpitations and episodes of dizziness. Holter monitor ordered.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC103', condition: 'Hyperthyroidism', diagnosedDate: '2020-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 88,
    respiration_rate: 18,
    bp_systolic: 120,
    bp_diastolic: 80,
  },
  {
    id: 'CARD003',
    name: 'Amit Patel',
    age: 62,
    gender: 'Male',
    dob: '1961-11-30',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Kavita Patel',
    phoneNumber: '9876543212',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest discomfort', 'Fatigue'],
    surgeries: ['Bypass Surgery (2017)'],
    triageInfo: {
      chiefComplaint: 'Chest discomfort and fatigue',
      risk: 'High',
      riskScore: 75,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with history of bypass surgery presenting with chest discomfort and fatigue.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC104', condition: 'Hypertension', diagnosedDate: '2010-01-01' },
        { id: 'PC105', condition: 'Hyperlipidemia', diagnosedDate: '2012-01-01' },
      ],
      surgeries: [
        { id: 'S102', procedure: 'Coronary Artery Bypass Graft', date: '2017-03-15' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.7,
    heart_rate_bpm: 78,
    respiration_rate: 16,
    bp_systolic: 135,
    bp_diastolic: 85,
  },
  {
    id: 'CARD004',
    name: 'Sneha Reddy',
    age: 38,
    gender: 'Female',
    dob: '1985-02-14',
    bloodType: 'AB+',
    maritalStatus: 'Single',
    guardianName: 'Venkat Reddy',
    phoneNumber: '9876543213',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest tightness', 'Anxiety'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Chest tightness and anxiety',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with chest tightness and anxiety. Likely musculoskeletal pain.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC106', condition: 'Anxiety Disorder', diagnosedDate: '2019-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 95,
    respiration_rate: 20,
    bp_systolic: 118,
    bp_diastolic: 76,
  },
  {
    id: 'CARD005',
    name: 'Vikram Singh',
    age: 70,
    gender: 'Male',
    dob: '1953-09-05',
    bloodType: 'O-',
    maritalStatus: 'Widowed',
    guardianName: 'Ritu Singh',
    phoneNumber: '9876543214',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe chest pain', 'Nausea'],
    surgeries: ['Pacemaker (2021)'],
    triageInfo: {
      chiefComplaint: 'Severe chest pain and nausea',
      risk: 'High',
      riskScore: 90,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with severe chest pain and nausea. Rule out MI.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC107', condition: 'Hypertension', diagnosedDate: '2005-01-01' },
        { id: 'PC108', condition: 'Diabetes', diagnosedDate: '2010-01-01' },
      ],
      surgeries: [
        { id: 'S103', procedure: 'Pacemaker Implantation', date: '2021-07-10' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.1,
    heart_rate_bpm: 105,
    respiration_rate: 24,
    bp_systolic: 150,
    bp_diastolic: 95,
  },
  {
    id: 'CARD006',
    name: 'Anjali Mehta',
    age: 52,
    gender: 'Female',
    dob: '1971-12-18',
    bloodType: 'A+',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Mehta',
    phoneNumber: '9876543215',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Shortness of breath', 'Swelling in legs'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Shortness of breath and leg swelling',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with shortness of breath and peripheral edema. Evaluate for heart failure.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC109', condition: 'Hypertension', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 85,
    respiration_rate: 20,
    bp_systolic: 140,
    bp_diastolic: 88,
  },
  {
    id: 'CARD007',
    name: 'Rahul Verma',
    age: 48,
    gender: 'Male',
    dob: '1975-04-25',
    bloodType: 'B-',
    maritalStatus: 'Married',
    guardianName: 'Sunita Verma',
    phoneNumber: '9876543216',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pain on exertion', 'Fatigue'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Exertional chest pain and fatigue',
      risk: 'Medium',
      riskScore: 70,
      triageDate: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with exertional chest pain. Stress test indicated.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC110', condition: 'Hyperlipidemia', diagnosedDate: '2018-01-01' },
        { id: 'PC111', condition: 'Family History of CAD', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 82,
    respiration_rate: 18,
    bp_systolic: 130,
    bp_diastolic: 82,
  },
  {
    id: 'CARD008',
    name: 'Kavita Nair',
    age: 55,
    gender: 'Female',
    dob: '1968-08-30',
    bloodType: 'AB-',
    maritalStatus: 'Divorced',
    guardianName: 'Manoj Nair',
    phoneNumber: '9876543217',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Palpitations', 'Chest fluttering'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Palpitations and chest fluttering',
      risk: 'Low',
      riskScore: 40,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with palpitations and chest fluttering. Likely benign arrhythmia.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC112', condition: 'Anxiety', diagnosedDate: '2017-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 90,
    respiration_rate: 18,
    bp_systolic: 122,
    bp_diastolic: 78,
  },
  {
    id: 'CARD009',
    name: 'Deepak Gupta',
    age: 65,
    gender: 'Male',
    dob: '1958-01-12',
    bloodType: 'O+',
    maritalStatus: 'Married',
    guardianName: 'Sunita Gupta',
    phoneNumber: '9876543218',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pressure', 'Weakness'],
    surgeries: ['Stent Placement (2020)'],
    triageInfo: {
      chiefComplaint: 'Chest pressure and weakness',
      risk: 'High',
      riskScore: 80,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with history of stent placement presenting with chest pressure.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC113', condition: 'Hypertension', diagnosedDate: '2010-01-01' },
        { id: 'PC114', condition: 'Diabetes', diagnosedDate: '2012-01-01' },
      ],
      surgeries: [
        { id: 'S104', procedure: 'Coronary Stent Placement', date: '2020-11-05' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.8,
    heart_rate_bpm: 88,
    respiration_rate: 20,
    bp_systolic: 142,
    bp_diastolic: 89,
  },
  {
    id: 'CARD010',
    name: 'Meera Iyer',
    age: 40,
    gender: 'Female',
    dob: '1983-06-08',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Prakash Iyer',
    phoneNumber: '9876543219',
    assignedDoctorId: 'DOC001',
    department: 'Cardiology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pain', 'Anxiety'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Chest pain and anxiety',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young female with chest pain and anxiety. Likely non-cardiac chest pain.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC115', condition: 'Anxiety Disorder', diagnosedDate: '2020-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 92,
    respiration_rate: 19,
    bp_systolic: 119,
    bp_diastolic: 77,
  },

  // Neurology Department (10 patients)
  {
    id: 'NEURO001',
    name: 'Sanjay Malhotra',
    age: 60,
    gender: 'Male',
    dob: '1963-05-15',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Rekha Malhotra',
    phoneNumber: '9876543220',
    assignedDoctorId: 'DOC003',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe headache', 'Nausea'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe headache and nausea',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with sudden onset severe headache. Rule out subarachnoid hemorrhage.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC201', condition: 'Hypertension', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 88,
    respiration_rate: 18,
    bp_systolic: 150,
    bp_diastolic: 92,
  },
  {
    id: 'NEURO002',
    name: 'Neha Kapoor',
    age: 35,
    gender: 'Female',
    dob: '1988-09-22',
    bloodType: 'A-',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Kapoor',
    phoneNumber: '9876543221',
    assignedDoctorId: 'DOC004',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Seizures', 'Confusion'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Seizures and confusion',
      risk: 'High',
      riskScore: 80,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with new onset seizures and post-ictal confusion. MRI brain ordered.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 85,
    respiration_rate: 16,
    bp_systolic: 120,
    bp_diastolic: 80,
  },
  {
    id: 'NEURO003',
    name: 'Vijay Rao',
    age: 72,
    gender: 'Male',
    dob: '1951-03-30',
    bloodType: 'O+',
    maritalStatus: 'Widowed',
    guardianName: 'Anita Rao',
    phoneNumber: '9876543222',
    assignedDoctorId: 'DOC003',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Memory loss', 'Confusion'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Memory loss and confusion',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with progressive memory loss and confusion. Evaluate for dementia.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC202', condition: 'Hypertension', diagnosedDate: '2010-01-01' },
        { id: 'PC203', condition: 'Diabetes', diagnosedDate: '2012-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 78,
    respiration_rate: 16,
    bp_systolic: 135,
    bp_diastolic: 82,
  },
  {
    id: 'NEURO004',
    name: 'Pooja Desai',
    age: 28,
    gender: 'Female',
    dob: '1995-07-14',
    bloodType: 'AB+',
    maritalStatus: 'Married',
    guardianName: 'Mukesh Desai',
    phoneNumber: '9876543223',
    assignedDoctorId: 'DOC004',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Headache', 'Visual disturbances'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Headache and visual disturbances',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with headache and visual disturbances. Rule out migraine with aura.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC204', condition: 'Migraine', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 82,
    respiration_rate: 17,
    bp_systolic: 118,
    bp_diastolic: 76,
  },
  {
    id: 'NEURO005',
    name: 'Ramesh Pillai',
    age: 55,
    gender: 'Male',
    dob: '1968-11-05',
    bloodType: 'B-',
    maritalStatus: 'Married',
    guardianName: 'Lakshmi Pillai',
    phoneNumber: '9876543224',
    assignedDoctorId: 'DOC003',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Weakness in left arm', 'Slurred speech'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Left arm weakness and slurred speech',
      risk: 'High',
      riskScore: 90,
      triageDate: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with acute onset left arm weakness and slurred speech. Rule out stroke.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC205', condition: 'Hypertension', diagnosedDate: '2012-01-01' },
        { id: 'PC206', condition: 'Diabetes', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.7,
    heart_rate_bpm: 95,
    respiration_rate: 20,
    bp_systolic: 160,
    bp_diastolic: 95,
  },
  {
    id: 'NEURO006',
    name: 'Sunita Menon',
    age: 42,
    gender: 'Female',
    dob: '1981-02-18',
    bloodType: 'A+',
    maritalStatus: 'Divorced',
    guardianName: 'Ravi Menon',
    phoneNumber: '9876543225',
    assignedDoctorId: 'DOC004',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Tingling in hands', 'Numbness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Tingling in hands and numbness',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with tingling and numbness in hands. Likely peripheral neuropathy.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC207', condition: 'Diabetes', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 80,
    respiration_rate: 16,
    bp_systolic: 122,
    bp_diastolic: 78,
  },
  {
    id: 'NEURO007',
    name: 'Anil Bhatia',
    age: 68,
    gender: 'Male',
    dob: '1955-08-25',
    bloodType: 'O-',
    maritalStatus: 'Married',
    guardianName: 'Sunita Bhatia',
    phoneNumber: '9876543226',
    assignedDoctorId: 'DOC003',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Tremors', 'Slow movements'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Tremors and slow movements',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with tremors and bradykinesia. Evaluate for Parkinson\'s disease.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC208', condition: 'Hypertension', diagnosedDate: '2010-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 76,
    respiration_rate: 16,
    bp_systolic: 138,
    bp_diastolic: 84,
  },
  {
    id: 'NEURO008',
    name: 'Kavita Joshi',
    age: 33,
    gender: 'Female',
    dob: '1990-04-30',
    bloodType: 'AB-',
    maritalStatus: 'Single',
    guardianName: 'Prakash Joshi',
    phoneNumber: '9876543227',
    assignedDoctorId: 'DOC004',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe back pain', 'Leg weakness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe back pain and leg weakness',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with back pain and leg weakness. Rule out spinal cord compression.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 84,
    respiration_rate: 18,
    bp_systolic: 120,
    bp_diastolic: 79,
  },
  {
    id: 'NEURO009',
    name: 'Rajiv Khanna',
    age: 50,
    gender: 'Male',
    dob: '1973-12-12',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Smita Khanna',
    phoneNumber: '9876543228',
    assignedDoctorId: 'DOC003',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Fainting episodes', 'Dizziness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Fainting episodes and dizziness',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with recurrent syncope. Evaluate for cardiac and neurological causes.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC209', condition: 'Hypertension', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 86,
    respiration_rate: 17,
    bp_systolic: 130,
    bp_diastolic: 85,
  },
  {
    id: 'NEURO010',
    name: 'Shalini Verma',
    age: 29,
    gender: 'Female',
    dob: '1994-06-08',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Verma',
    phoneNumber: '9876543229',
    assignedDoctorId: 'DOC004',
    department: 'Neurology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe headaches', 'Nausea'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe headaches and nausea',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with severe headaches and nausea. Likely migraine.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC210', condition: 'Migraine', diagnosedDate: '2016-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 81,
    respiration_rate: 16,
    bp_systolic: 119,
    bp_diastolic: 77,
  },

  // Orthopedics Department (10 patients)
  {
    id: 'ORTH001',
    name: 'Manoj Kumar',
    age: 45,
    gender: 'Male',
    dob: '1978-03-15',
    bloodType: 'O+',
    maritalStatus: 'Married',
    guardianName: 'Sunita Kumar',
    phoneNumber: '9876543230',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Knee pain', 'Difficulty walking'],
    surgeries: ['Knee Replacement (2022)'],
    triageInfo: {
      chiefComplaint: 'Knee pain and difficulty walking',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with severe knee pain and difficulty walking. History of knee replacement.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC301', condition: 'Osteoarthritis', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [
        { id: 'S301', procedure: 'Total Knee Replacement', date: '2022-05-20' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 82,
    respiration_rate: 17,
    bp_systolic: 125,
    bp_diastolic: 80,
  },
  {
    id: 'ORTH002',
    name: 'Radhika Sharma',
    age: 32,
    gender: 'Female',
    dob: '1991-07-22',
    bloodType: 'A-',
    maritalStatus: 'Single',
    guardianName: 'Ramesh Sharma',
    phoneNumber: '9876543231',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Back pain', 'Sciatica'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Back pain and sciatica',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with back pain radiating to leg. Likely herniated disc.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 78,
    respiration_rate: 16,
    bp_systolic: 120,
    bp_diastolic: 78,
  },
  {
    id: 'ORTH003',
    name: 'Vikas Patel',
    age: 58,
    gender: 'Male',
    dob: '1965-11-30',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Kavita Patel',
    phoneNumber: '9876543232',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Hip pain', 'Difficulty standing'],
    surgeries: ['Hip Replacement (2020)'],
    triageInfo: {
      chiefComplaint: 'Hip pain and difficulty standing',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with hip pain and difficulty standing. History of hip replacement.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC302', condition: 'Osteoarthritis', diagnosedDate: '2012-01-01' },
      ],
      surgeries: [
        { id: 'S302', procedure: 'Total Hip Replacement', date: '2020-03-15' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 80,
    respiration_rate: 16,
    bp_systolic: 130,
    bp_diastolic: 82,
  },
  {
    id: 'ORTH004',
    name: 'Sneha Reddy',
    age: 25,
    gender: 'Female',
    dob: '1998-02-14',
    bloodType: 'AB+',
    maritalStatus: 'Single',
    guardianName: 'Venkat Reddy',
    phoneNumber: '9876543233',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Ankle sprain', 'Swelling'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Ankle sprain and swelling',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with ankle sprain and swelling. Likely ligament injury.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 76,
    respiration_rate: 16,
    bp_systolic: 118,
    bp_diastolic: 76,
  },
  {
    id: 'ORTH005',
    name: 'Raj Singh',
    age: 65,
    gender: 'Male',
    dob: '1958-09-05',
    bloodType: 'O-',
    maritalStatus: 'Widowed',
    guardianName: 'Ritu Singh',
    phoneNumber: '9876543234',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Shoulder pain', 'Limited movement'],
    surgeries: ['Rotator Cuff Repair (2021)'],
    triageInfo: {
      chiefComplaint: 'Shoulder pain and limited movement',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with shoulder pain and limited movement. History of rotator cuff repair.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC303', condition: 'Rotator Cuff Tear', diagnosedDate: '2019-01-01' },
      ],
      surgeries: [
        { id: 'S303', procedure: 'Rotator Cuff Repair', date: '2021-07-10' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 78,
    respiration_rate: 16,
    bp_systolic: 135,
    bp_diastolic: 84,
  },
  {
    id: 'ORTH006',
    name: 'Anjali Mehta',
    age: 40,
    gender: 'Female',
    dob: '1983-12-18',
    bloodType: 'A+',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Mehta',
    phoneNumber: '9876543235',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Wrist pain', 'Swelling'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Wrist pain and swelling',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with wrist pain and swelling. Likely fracture or sprain.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 77,
    respiration_rate: 16,
    bp_systolic: 122,
    bp_diastolic: 78,
  },
  {
    id: 'ORTH007',
    name: 'Rahul Verma',
    age: 52,
    gender: 'Male',
    dob: '1971-04-25',
    bloodType: 'B-',
    maritalStatus: 'Married',
    guardianName: 'Sunita Verma',
    phoneNumber: '9876543236',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Neck pain', 'Numbness in arms'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Neck pain and arm numbness',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with neck pain and arm numbness. Likely cervical radiculopathy.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC304', condition: 'Cervical Spondylosis', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 80,
    respiration_rate: 17,
    bp_systolic: 128,
    bp_diastolic: 80,
  },
  {
    id: 'ORTH008',
    name: 'Kavita Nair',
    age: 38,
    gender: 'Female',
    dob: '1985-08-30',
    bloodType: 'AB-',
    maritalStatus: 'Divorced',
    guardianName: 'Manoj Nair',
    phoneNumber: '9876543237',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Elbow pain', 'Difficulty lifting'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Elbow pain and difficulty lifting',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with elbow pain and difficulty lifting. Likely tennis elbow.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 76,
    respiration_rate: 16,
    bp_systolic: 120,
    bp_diastolic: 77,
  },
  {
    id: 'ORTH009',
    name: 'Deepak Gupta',
    age: 70,
    gender: 'Male',
    dob: '1953-01-12',
    bloodType: 'O+',
    maritalStatus: 'Married',
    guardianName: 'Sunita Gupta',
    phoneNumber: '9876543238',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Knee pain', 'Stiffness'],
    surgeries: ['Knee Arthroscopy (2019)'],
    triageInfo: {
      chiefComplaint: 'Knee pain and stiffness',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with knee pain and stiffness. History of knee arthroscopy.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC305', condition: 'Osteoarthritis', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [
        { id: 'S304', procedure: 'Knee Arthroscopy', date: '2019-11-05' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 78,
    respiration_rate: 16,
    bp_systolic: 138,
    bp_diastolic: 85,
  },
  {
    id: 'ORTH010',
    name: 'Meera Iyer',
    age: 29,
    gender: 'Female',
    dob: '1994-06-08',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Prakash Iyer',
    phoneNumber: '9876543239',
    assignedDoctorId: 'DOC002',
    department: 'Orthopedics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Foot pain', 'Difficulty walking'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Foot pain and difficulty walking',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with foot pain and difficulty walking. Likely plantar fasciitis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 77,
    respiration_rate: 16,
    bp_systolic: 119,
    bp_diastolic: 77,
  },

  // General Medicine Department (10 patients)
  {
    id: 'GEN001',
    name: 'Amitabh Chatterjee',
    age: 55,
    gender: 'Male',
    dob: '1968-05-15',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Sunita Chatterjee',
    phoneNumber: '9876543240',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Fever', 'Cough', 'Fatigue'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Fever, cough, and fatigue',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with fever, cough, and fatigue. Likely respiratory infection.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC401', condition: 'Hypertension', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 101.2,
    heart_rate_bpm: 92,
    respiration_rate: 20,
    bp_systolic: 140,
    bp_diastolic: 88,
  },
  {
    id: 'GEN002',
    name: 'Priya Nair',
    age: 32,
    gender: 'Female',
    dob: '1991-09-22',
    bloodType: 'A-',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Nair',
    phoneNumber: '9876543241',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Abdominal pain', 'Nausea'],
    surgeries: ['Appendectomy (2018)'],
    triageInfo: {
      chiefComplaint: 'Abdominal pain and nausea',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with abdominal pain and nausea. Rule out gastrointestinal issue.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [
        { id: 'S401', procedure: 'Appendectomy', date: '2018-05-15' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.8,
    heart_rate_bpm: 88,
    respiration_rate: 18,
    bp_systolic: 120,
    bp_diastolic: 80,
  },
  {
    id: 'GEN003',
    name: 'Rajesh Pillai',
    age: 68,
    gender: 'Male',
    dob: '1955-03-30',
    bloodType: 'O+',
    maritalStatus: 'Widowed',
    guardianName: 'Anita Pillai',
    phoneNumber: '9876543242',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Weight loss', 'Fatigue', 'Night sweats'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Weight loss, fatigue, and night sweats',
      risk: 'High',
      riskScore: 80,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with constitutional symptoms. Rule out malignancy or infection.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC402', condition: 'Diabetes', diagnosedDate: '2012-01-01' },
        { id: 'PC403', condition: 'Hypertension', diagnosedDate: '2010-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.9,
    heart_rate_bpm: 85,
    respiration_rate: 18,
    bp_systolic: 135,
    bp_diastolic: 82,
  },
  {
    id: 'GEN004',
    name: 'Sunita Menon',
    age: 28,
    gender: 'Female',
    dob: '1995-07-14',
    bloodType: 'AB+',
    maritalStatus: 'Married',
    guardianName: 'Mukesh Menon',
    phoneNumber: '9876543243',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Headache', 'Dizziness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Headache and dizziness',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with headache and dizziness. Likely tension headache.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC404', condition: 'Migraine', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 82,
    respiration_rate: 17,
    bp_systolic: 118,
    bp_diastolic: 76,
  },
  {
    id: 'GEN005',
    name: 'Anil Bhatia',
    age: 62,
    gender: 'Male',
    dob: '1961-11-05',
    bloodType: 'B-',
    maritalStatus: 'Married',
    guardianName: 'Lakshmi Bhatia',
    phoneNumber: '9876543244',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pain', 'Shortness of breath'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Chest pain and shortness of breath',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with chest pain and shortness of breath. Rule out cardiac issue.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC405', condition: 'Hypertension', diagnosedDate: '2012-01-01' },
        { id: 'PC406', condition: 'Diabetes', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.1,
    heart_rate_bpm: 95,
    respiration_rate: 22,
    bp_systolic: 150,
    bp_diastolic: 92,
  },
  {
    id: 'GEN006',
    name: 'Kavita Joshi',
    age: 45,
    gender: 'Female',
    dob: '1978-02-18',
    bloodType: 'A+',
    maritalStatus: 'Divorced',
    guardianName: 'Ravi Joshi',
    phoneNumber: '9876543245',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Joint pain', 'Morning stiffness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Joint pain and morning stiffness',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with joint pain and morning stiffness. Likely inflammatory arthritis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 80,
    respiration_rate: 16,
    bp_systolic: 122,
    bp_diastolic: 78,
  },
  {
    id: 'GEN007',
    name: 'Rajiv Khanna',
    age: 58,
    gender: 'Male',
    dob: '1965-08-25',
    bloodType: 'O-',
    maritalStatus: 'Married',
    guardianName: 'Smita Khanna',
    phoneNumber: '9876543246',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Frequent urination', 'Increased thirst'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Frequent urination and increased thirst',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with frequent urination and increased thirst. Rule out diabetes.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC407', condition: 'Pre-diabetes', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 84,
    respiration_rate: 17,
    bp_systolic: 130,
    bp_diastolic: 85,
  },
  {
    id: 'GEN008',
    name: 'Shalini Verma',
    age: 35,
    gender: 'Female',
    dob: '1988-04-30',
    bloodType: 'AB-',
    maritalStatus: 'Single',
    guardianName: 'Prakash Verma',
    phoneNumber: '9876543247',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Sore throat', 'Fever'],
    surgeries: ['Tonsillectomy (2005)'],
    triageInfo: {
      chiefComplaint: 'Sore throat and fever',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with sore throat and fever. Likely viral pharyngitis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [
        { id: 'S402', procedure: 'Tonsillectomy', date: '2005-08-15' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 100.5,
    heart_rate_bpm: 86,
    respiration_rate: 18,
    bp_systolic: 120,
    bp_diastolic: 79,
  },
  {
    id: 'GEN009',
    name: 'Manoj Reddy',
    age: 50,
    gender: 'Male',
    dob: '1973-12-12',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Sunita Reddy',
    phoneNumber: '9876543248',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Fatigue', 'Pale skin'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Fatigue and pale skin',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with fatigue and pallor. Rule out anemia.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 88,
    respiration_rate: 17,
    bp_systolic: 125,
    bp_diastolic: 80,
  },
  {
    id: 'GEN010',
    name: 'Radhika Sharma',
    age: 29,
    gender: 'Female',
    dob: '1994-06-08',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Sharma',
    phoneNumber: '9876543249',
    assignedDoctorId: 'DOC007',
    department: 'General Medicine',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Nausea', 'Vomiting', 'Diarrhea'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Nausea, vomiting, and diarrhea',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with nausea, vomiting, and diarrhea. Likely gastroenteritis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.7,
    heart_rate_bpm: 90,
    respiration_rate: 18,
    bp_systolic: 119,
    bp_diastolic: 77,
  },

  // Pediatrics Department (10 patients)
  {
    id: 'PED001',
    name: 'Arjun Kumar',
    age: 8,
    gender: 'Male',
    dob: '2015-03-15',
    bloodType: 'O+',
    maritalStatus: 'Single',
    guardianName: 'Sunita Kumar',
    phoneNumber: '9876543250',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Fever', 'Cough', 'Runny nose'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Fever, cough, and runny nose',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with fever, cough, and runny nose. Likely viral upper respiratory infection.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 100.8,
    heart_rate_bpm: 110,
    respiration_rate: 24,
    bp_systolic: 100,
    bp_diastolic: 65,
  },
  {
    id: 'PED002',
    name: 'Ananya Sharma',
    age: 5,
    gender: 'Female',
    dob: '2018-09-22',
    bloodType: 'A-',
    maritalStatus: 'Single',
    guardianName: 'Ramesh Sharma',
    phoneNumber: '9876543251',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Abdominal pain', 'Vomiting'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Abdominal pain and vomiting',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with abdominal pain and vomiting. Rule out gastroenteritis or appendicitis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.9,
    heart_rate_bpm: 105,
    respiration_rate: 22,
    bp_systolic: 95,
    bp_diastolic: 60,
  },
  {
    id: 'PED003',
    name: 'Rohan Patel',
    age: 12,
    gender: 'Male',
    dob: '2011-03-30',
    bloodType: 'B+',
    maritalStatus: 'Single',
    guardianName: 'Kavita Patel',
    phoneNumber: '9876543252',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Sore throat', 'Fever', 'Difficulty swallowing'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Sore throat, fever, and difficulty swallowing',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with sore throat, fever, and difficulty swallowing. Rule out strep throat.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 101.5,
    heart_rate_bpm: 115,
    respiration_rate: 26,
    bp_systolic: 105,
    bp_diastolic: 68,
  },
  {
    id: 'PED004',
    name: 'Isha Reddy',
    age: 3,
    gender: 'Female',
    dob: '2020-07-14',
    bloodType: 'AB+',
    maritalStatus: 'Single',
    guardianName: 'Venkat Reddy',
    phoneNumber: '9876543253',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['High fever', 'Irritability'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'High fever and irritability',
      risk: 'High',
      riskScore: 80,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young child with high fever and irritability. Rule out serious bacterial infection.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 103.2,
    heart_rate_bpm: 140,
    respiration_rate: 32,
    bp_systolic: 90,
    bp_diastolic: 58,
  },
  {
    id: 'PED005',
    name: 'Aryan Singh',
    age: 10,
    gender: 'Male',
    dob: '2013-11-05',
    bloodType: 'O-',
    maritalStatus: 'Single',
    guardianName: 'Ritu Singh',
    phoneNumber: '9876543254',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Joint pain', 'Rash'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Joint pain and rash',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with joint pain and rash. Rule out rheumatic fever or other inflammatory conditions.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 100.2,
    heart_rate_bpm: 110,
    respiration_rate: 22,
    bp_systolic: 102,
    bp_diastolic: 66,
  },
  {
    id: 'PED006',
    name: 'Kiara Mehta',
    age: 7,
    gender: 'Female',
    dob: '2016-02-18',
    bloodType: 'A+',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Mehta',
    phoneNumber: '9876543255',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Ear pain', 'Fever'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Ear pain and fever',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with ear pain and fever. Likely acute otitis media.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 101.0,
    heart_rate_bpm: 112,
    respiration_rate: 24,
    bp_systolic: 98,
    bp_diastolic: 62,
  },
  {
    id: 'PED007',
    name: 'Dev Verma',
    age: 14,
    gender: 'Male',
    dob: '2009-08-25',
    bloodType: 'B-',
    maritalStatus: 'Single',
    guardianName: 'Sunita Verma',
    phoneNumber: '9876543256',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Headache', 'Blurred vision'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Headache and blurred vision',
      risk: 'Medium',
      riskScore: 55,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Adolescent with headache and blurred vision. Rule out refractive error or increased intracranial pressure.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 85,
    respiration_rate: 18,
    bp_systolic: 110,
    bp_diastolic: 70,
  },
  {
    id: 'PED008',
    name: 'Neha Nair',
    age: 6,
    gender: 'Female',
    dob: '2017-04-30',
    bloodType: 'AB-',
    maritalStatus: 'Single',
    guardianName: 'Manoj Nair',
    phoneNumber: '9876543257',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Wheezing', 'Shortness of breath'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Wheezing and shortness of breath',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with wheezing and shortness of breath. Likely asthma exacerbation.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC501', condition: 'Asthma', diagnosedDate: '2020-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.8,
    heart_rate_bpm: 120,
    respiration_rate: 28,
    bp_systolic: 100,
    bp_diastolic: 65,
  },
  {
    id: 'PED009',
    name: 'Rohan Khanna',
    age: 9,
    gender: 'Male',
    dob: '2014-12-12',
    bloodType: 'O+',
    maritalStatus: 'Single',
    guardianName: 'Smita Khanna',
    phoneNumber: '9876543258',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Abdominal pain', 'Constipation'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Abdominal pain and constipation',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with abdominal pain and constipation. Likely functional constipation.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 95,
    respiration_rate: 20,
    bp_systolic: 105,
    bp_diastolic: 68,
  },
  {
    id: 'PED010',
    name: 'Anaya Verma',
    age: 4,
    gender: 'Female',
    dob: '2019-06-08',
    bloodType: 'A-',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Verma',
    phoneNumber: '9876543259',
    assignedDoctorId: 'DOC005',
    department: 'Pediatrics',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Fever', 'Rash'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Fever and rash',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Child with fever and rash. Likely viral exanthem.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 100.5,
    heart_rate_bpm: 110,
    respiration_rate: 22,
    bp_systolic: 97,
    bp_diastolic: 63,
  },

  // Emergency Department (10 patients)
  {
    id: 'EMER001',
    name: 'Vikram Malhotra',
    age: 35,
    gender: 'Male',
    dob: '1988-05-15',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Rekha Malhotra',
    phoneNumber: '9876543260',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pain', 'Shortness of breath', 'Sweating'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe chest pain, shortness of breath, and sweating',
      risk: 'High',
      riskScore: 95,
      triageDate: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with severe chest pain, shortness of breath, and diaphoresis. Rule out acute myocardial infarction.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC601', condition: 'Hypertension', diagnosedDate: '2018-01-01' },
        { id: 'PC602', condition: 'Smoking', diagnosedDate: '2010-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.7,
    heart_rate_bpm: 110,
    respiration_rate: 24,
    bp_systolic: 160,
    bp_diastolic: 95,
  },
  {
    id: 'EMER002',
    name: 'Sneha Kapoor',
    age: 28,
    gender: 'Female',
    dob: '1995-09-22',
    bloodType: 'A-',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Kapoor',
    phoneNumber: '9876543261',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe headache', 'Neck stiffness', 'Fever'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe headache, neck stiffness, and fever',
      risk: 'High',
      riskScore: 90,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with severe headache, neck stiffness, and fever. Rule out bacterial meningitis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 102.5,
    heart_rate_bpm: 120,
    respiration_rate: 22,
    bp_systolic: 110,
    bp_diastolic: 70,
  },
  {
    id: 'EMER003',
    name: 'Rajesh Rao',
    age: 65,
    gender: 'Male',
    dob: '1958-03-30',
    bloodType: 'O+',
    maritalStatus: 'Widowed',
    guardianName: 'Anita Rao',
    phoneNumber: '9876543262',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Weakness', 'Slurred speech', 'Facial droop'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Sudden weakness, slurred speech, and facial droop',
      risk: 'High',
      riskScore: 95,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Elderly patient with sudden onset weakness, slurred speech, and facial droop. Rule out acute stroke.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC603', condition: 'Hypertension', diagnosedDate: '2010-01-01' },
        { id: 'PC604', condition: 'Diabetes', diagnosedDate: '2012-01-01' },
        { id: 'PC605', condition: 'Atrial Fibrillation', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 95,
    respiration_rate: 18,
    bp_systolic: 180,
    bp_diastolic: 100,
  },
  {
    id: 'EMER004',
    name: 'Pooja Desai',
    age: 22,
    gender: 'Female',
    dob: '2001-07-14',
    bloodType: 'AB+',
    maritalStatus: 'Single',
    guardianName: 'Mukesh Desai',
    phoneNumber: '9876543263',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Abdominal pain', 'Vomiting', 'Fever'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe abdominal pain, vomiting, and fever',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Young patient with severe abdominal pain, vomiting, and fever. Rule out appendicitis or other surgical abdomen.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 101.8,
    heart_rate_bpm: 115,
    respiration_rate: 20,
    bp_systolic: 120,
    bp_diastolic: 80,
  },
  {
    id: 'EMER005',
    name: 'Ramesh Pillai',
    age: 45,
    gender: 'Male',
    dob: '1978-11-05',
    bloodType: 'B-',
    maritalStatus: 'Married',
    guardianName: 'Lakshmi Pillai',
    phoneNumber: '9876543264',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest trauma', 'Difficulty breathing'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Chest trauma and difficulty breathing',
      risk: 'High',
      riskScore: 90,
      triageDate: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with chest trauma and difficulty breathing. Rule out pneumothorax or hemothorax.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.9,
    heart_rate_bpm: 125,
    respiration_rate: 28,
    bp_systolic: 100,
    bp_diastolic: 65,
  },
  {
    id: 'EMER006',
    name: 'Sunita Menon',
    age: 55,
    gender: 'Female',
    dob: '1968-02-18',
    bloodType: 'A+',
    maritalStatus: 'Divorced',
    guardianName: 'Ravi Menon',
    phoneNumber: '9876543265',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe back pain', 'Abdominal pain'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe back pain and abdominal pain',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with severe back pain and abdominal pain. Rule out aortic dissection or other vascular emergency.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC606', condition: 'Hypertension', diagnosedDate: '2012-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.2,
    heart_rate_bpm: 110,
    respiration_rate: 22,
    bp_systolic: 170,
    bp_diastolic: 100,
  },
  {
    id: 'EMER007',
    name: 'Anil Bhatia',
    age: 38,
    gender: 'Male',
    dob: '1985-08-25',
    bloodType: 'O-',
    maritalStatus: 'Married',
    guardianName: 'Sunita Bhatia',
    phoneNumber: '9876543266',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Seizure', 'Confusion'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Seizure and post-ictal confusion',
      risk: 'Medium',
      riskScore: 70,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with recent seizure and confusion. Rule out status epilepticus or other neurological emergency.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC607', condition: 'Epilepsy', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 95,
    respiration_rate: 18,
    bp_systolic: 130,
    bp_diastolic: 85,
  },
  {
    id: 'EMER008',
    name: 'Kavita Joshi',
    age: 30,
    gender: 'Female',
    dob: '1993-04-30',
    bloodType: 'AB-',
    maritalStatus: 'Single',
    guardianName: 'Prakash Joshi',
    phoneNumber: '9876543267',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Vaginal bleeding', 'Abdominal pain'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Vaginal bleeding and abdominal pain',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Female patient with vaginal bleeding and abdominal pain. Rule out ectopic pregnancy or other gynecological emergency.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 99.5,
    heart_rate_bpm: 120,
    respiration_rate: 20,
    bp_systolic: 110,
    bp_diastolic: 70,
  },
  {
    id: 'EMER009',
    name: 'Rajiv Khanna',
    age: 50,
    gender: 'Male',
    dob: '1973-12-12',
    bloodType: 'B+',
    maritalStatus: 'Married',
    guardianName: 'Smita Khanna',
    phoneNumber: '9876543268',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Chest pain', 'Palpitations', 'Dizziness'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Chest pain, palpitations, and dizziness',
      risk: 'Medium',
      riskScore: 75,
      triageDate: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with chest pain, palpitations, and dizziness. Rule out arrhythmia or other cardiac issue.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC608', condition: 'Hyperthyroidism', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.8,
    heart_rate_bpm: 130,
    respiration_rate: 20,
    bp_systolic: 125,
    bp_diastolic: 80,
  },
  {
    id: 'EMER010',
    name: 'Shalini Verma',
    age: 42,
    gender: 'Female',
    dob: '1981-06-08',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Verma',
    phoneNumber: '9876543269',
    assignedDoctorId: 'DOC007',
    department: 'Emergency',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe headache', 'Visual disturbances'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe headache and visual disturbances',
      risk: 'Medium',
      riskScore: 70,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with severe headache and visual disturbances. Rule out migraine or other neurological issue.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC609', condition: 'Migraine', diagnosedDate: '2016-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 90,
    respiration_rate: 18,
    bp_systolic: 120,
    bp_diastolic: 78,
  },

  // Gynecology Department (10 patients)
  {
    id: 'GYN001',
    name: 'Priya Sharma',
    age: 32,
    gender: 'Female',
    dob: '1991-05-15',
    bloodType: 'A-',
    maritalStatus: 'Married',
    guardianName: 'Ramesh Sharma',
    phoneNumber: '9876543270',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: true,
    symptoms: ['Vaginal bleeding', 'Abdominal pain'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Vaginal bleeding and abdominal pain in pregnancy',
      risk: 'High',
      riskScore: 90,
      triageDate: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Pregnant patient with vaginal bleeding and abdominal pain. Rule out miscarriage or ectopic pregnancy.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC701', condition: 'PCOS', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.7,
    heart_rate_bpm: 95,
    respiration_rate: 18,
    bp_systolic: 120,
    bp_diastolic: 80,
  },
  {
    id: 'GYN002',
    name: 'Sneha Reddy',
    age: 28,
    gender: 'Female',
    dob: '1995-09-22',
    bloodType: 'AB+',
    maritalStatus: 'Single',
    guardianName: 'Venkat Reddy',
    phoneNumber: '9876543271',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Pelvic pain', 'Irregular periods'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Pelvic pain and irregular periods',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with pelvic pain and irregular periods. Rule out endometriosis or PCOS.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC702', condition: 'Endometriosis', diagnosedDate: '2020-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 85,
    respiration_rate: 16,
    bp_systolic: 118,
    bp_diastolic: 76,
  },
  {
    id: 'GYN003',
    name: 'Anjali Mehta',
    age: 45,
    gender: 'Female',
    dob: '1978-03-30',
    bloodType: 'O+',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Mehta',
    phoneNumber: '9876543272',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Postmenopausal bleeding'],
    surgeries: ['Hysterectomy (2023)'],
    triageInfo: {
      chiefComplaint: 'Postmenopausal bleeding',
      risk: 'High',
      riskScore: 85,
      triageDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Postmenopausal patient with vaginal bleeding. Rule out endometrial cancer.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC703', condition: 'Uterine Fibroids', diagnosedDate: '2015-01-01' },
      ],
      surgeries: [
        { id: 'S701', procedure: 'Total Hysterectomy', date: '2023-05-15' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 80,
    respiration_rate: 16,
    bp_systolic: 135,
    bp_diastolic: 82,
  },
  {
    id: 'GYN004',
    name: 'Kavita Nair',
    age: 35,
    gender: 'Female',
    dob: '1988-07-14',
    bloodType: 'B-',
    maritalStatus: 'Divorced',
    guardianName: 'Manoj Nair',
    phoneNumber: '9876543273',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Severe menstrual pain', 'Heavy bleeding'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Severe menstrual pain and heavy bleeding',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with severe dysmenorrhea and menorrhagia. Rule out adenomyosis or fibroids.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC704', condition: 'Adenomyosis', diagnosedDate: '2020-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 88,
    respiration_rate: 17,
    bp_systolic: 122,
    bp_diastolic: 78,
  },
  {
    id: 'GYN005',
    name: 'Meera Iyer',
    age: 29,
    gender: 'Female',
    dob: '1994-11-05',
    bloodType: 'A+',
    maritalStatus: 'Married',
    guardianName: 'Prakash Iyer',
    phoneNumber: '9876543274',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: true,
    symptoms: ['Vaginal discharge', 'Itching'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Vaginal discharge and itching in pregnancy',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Pregnant patient with vaginal discharge and itching. Likely candidiasis.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 82,
    respiration_rate: 16,
    bp_systolic: 119,
    bp_diastolic: 77,
  },
  {
    id: 'GYN006',
    name: 'Radhika Sharma',
    age: 40,
    gender: 'Female',
    dob: '1983-02-18',
    bloodType: 'AB-',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Sharma',
    phoneNumber: '9876543275',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Breast lump', 'Nipple discharge'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Breast lump and nipple discharge',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with breast lump and nipple discharge. Rule out breast cancer.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC705', condition: 'Fibrocystic Breast Disease', diagnosedDate: '2018-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 84,
    respiration_rate: 16,
    bp_systolic: 120,
    bp_diastolic: 78,
  },
  {
    id: 'GYN007',
    name: 'Shalini Verma',
    age: 38,
    gender: 'Female',
    dob: '1985-08-25',
    bloodType: 'O-',
    maritalStatus: 'Married',
    guardianName: 'Rajesh Verma',
    phoneNumber: '9876543276',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Pelvic pain', 'Bloating'],
    surgeries: ['Ovarian Cyst Removal (2022)'],
    triageInfo: {
      chiefComplaint: 'Pelvic pain and bloating',
      risk: 'Medium',
      riskScore: 60,
      triageDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with pelvic pain and bloating. History of ovarian cysts.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC706', condition: 'Ovarian Cysts', diagnosedDate: '2020-01-01' },
      ],
      surgeries: [
        { id: 'S702', procedure: 'Ovarian Cyst Removal', date: '2022-03-10' },
      ],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.6,
    heart_rate_bpm: 86,
    respiration_rate: 17,
    bp_systolic: 125,
    bp_diastolic: 80,
  },
  {
    id: 'GYN008',
    name: 'Neha Kapoor',
    age: 33,
    gender: 'Female',
    dob: '1990-04-30',
    bloodType: 'B+',
    maritalStatus: 'Single',
    guardianName: 'Rajesh Kapoor',
    phoneNumber: '9876543277',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Irregular periods', 'Weight gain'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Irregular periods and weight gain',
      risk: 'Low',
      riskScore: 35,
      triageDate: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Patient with irregular periods and weight gain. Likely PCOS.',
    medicalHistory: {
      pastConditions: [
        { id: 'PC707', condition: 'PCOS', diagnosedDate: '2019-01-01' },
      ],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.4,
    heart_rate_bpm: 80,
    respiration_rate: 16,
    bp_systolic: 118,
    bp_diastolic: 76,
  },
  {
    id: 'GYN009',
    name: 'Sunita Menon',
    age: 50,
    gender: 'Female',
    dob: '1973-12-12',
    bloodType: 'A-',
    maritalStatus: 'Divorced',
    guardianName: 'Ravi Menon',
    phoneNumber: '9876543278',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: false,
    symptoms: ['Hot flashes', 'Night sweats'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Hot flashes and night sweats',
      risk: 'Low',
      riskScore: 30,
      triageDate: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Perimenopausal patient with hot flashes and night sweats.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.3,
    heart_rate_bpm: 78,
    respiration_rate: 16,
    bp_systolic: 120,
    bp_diastolic: 77,
  },
  {
    id: 'GYN010',
    name: 'Lakshmi Bhatia',
    age: 26,
    gender: 'Female',
    dob: '1997-06-08',
    bloodType: 'O+',
    maritalStatus: 'Married',
    guardianName: 'Anil Bhatia',
    phoneNumber: '9876543279',
    assignedDoctorId: 'DOC008',
    department: 'Gynecology',
    status: 'WAITING_FOR_DOCTOR',
    isPregnant: true,
    symptoms: ['Vaginal bleeding', 'Cramping'],
    surgeries: ['None'],
    triageInfo: {
      chiefComplaint: 'Vaginal bleeding and cramping in early pregnancy',
      risk: 'Medium',
      riskScore: 65,
      triageDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    clinicalNotes: 'Early pregnant patient with vaginal bleeding and cramping. Rule out threatened miscarriage.',
    medicalHistory: {
      pastConditions: [],
      surgeries: [],
    },
    prescriptions: [],
    referrals: [],
    temperature_F: 98.5,
    heart_rate_bpm: 90,
    respiration_rate: 17,
    bp_systolic: 115,
    bp_diastolic: 75,
  }
];